create table if not exists attacks (
  id bigint generated by default as identity primary key,
  attacker_name text,
  attacker_tag text,
  attacker_team text,
  attacker_team_id text,
  stars int,
  percent numeric,
  attack_order int,
  army text,
  base_style text,
  spell_tower text,
  defender_name text,
  defender_tag text,
  defender_team text,
  defender_team_id text,
  competition text,
  match_id text,
  link text,
  stream text,
  stream_link text,
  date date,
  created_at timestamptz default now()
);

alter table attacks enable row level security;

create policy "Public read" on attacks for select using (true);
create policy "Public insert" on attacks for insert with check (true);
create policy "Public update" on attacks for update using (true);
create policy "Public delete" on attacks for delete using (true);
